name: build matrix demo

on:
  push: 
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      # By default, GitHub will maximize the number of jobs run in parallel
      # depending on the available runners on GitHub-hosted virtual machines.
      # max-parallel: 8
      fail-fast: false
      matrix:
        include:
          - django-verison: 1.11.0
            python-version: 2.7
          - django-verison: 1.11.0
            python-version: 3.4
          - django-verison: 1.11.0
            python-version: 3.5
          - django-verison: 1.11.0
            python-version: 3.6
          - django-verison: 1.11.0
            python-version: 3.7
          # Django 2.0
          - django-verison: 2.0.0
            python-version: 3.4
          - django-verison: 2.0.0
            python-version: 3.5
          - django-verison: 2.0.0
            python-version: 3.6
          - django-verison: 2.0.0
            python-version: 3.7
          # Django 2.1
          - django-verison: 2.1.0
            python-version: 3.5
          - django-verison: 2.1.0
            python-version: 3.6
          - django-verison: 2.1.0
            python-version: 3.7
          # Django 2.2
          - django-verison: 2.2.0
            python-version: 3.5
          - django-verison: 2.2.0
            python-version: 3.6
          - django-verison: 2.2.0
            python-version: 3.7
          - django-verison: 2.2.0
            python-version: 3.8
          - django-verison: 2.2.0
            python-version: 3.9
          # Django 3.0
          - django-verison: 3.0.0
            python-version: 3.6
          - django-verison: 3.0.0
            python-version: 3.7
          - django-verison: 3.0.0
            python-version: 3.8
          - django-verison: 3.0.0
            python-version: 3.9
          # Django 3.1
          - django-verison: 3.1.0
            python-version: 3.6
          - django-verison: 3.1.0
            python-version: 3.7
          - django-verison: 3.1.0
            python-version: 3.8
          - django-verison: 3.1.0
            python-version: 3.9
          # Django 3.2
          - django-verison: 3.2.0
            python-version: 3.6
          - django-verison: 3.2.0
            python-version: 3.7
          - django-verison: 3.2.0
            python-version: 3.8
          - django-verison: 3.2.0
            python-version: 3.9
          - django-verison: 3.2.0
            python-version: 3.10
        # python-version:
        #   - "2.7"
        #   - "3.6"
        #   - "3.7"
        #   - "3.8"
        #   - "3.9"
        #   - "3.10"
        # django-version:
        #   - "1.11.0"  # LTS
        #   - "2.0.0"
        #   - "2.1.0"
        #   - "2.2.0"  # LTS
        #   - "3.0.0"
        #   - "3.1.0"
        #   - "3.2.0"  # LTS
        #   - "4.0b1"
        # exclude:
        #   # Python 2.7 is compatible with Django 1.11
        #   - python-version: "2.7"
        #     django-version: "2.0.0"
        #   - python-version: "2.7"
        #     django-version: "2.1.0"
        #   - python-version: "2.7"
        #     django-version: "2.2.0"
        #   - python-version: "2.7"
        #     django-version: "3.0.0"
        #   - python-version: "2.7"
        #     django-version: "3.1.0"
        #   - python-version: "2.7"
        #     django-version: "3.2.0"
        #   - python-version: "2.7"
        #     django-version: "4.0b1"
        #   # Python 3.6 is compatible with Django 4.0b1
        #   - python-version: "3.6"
        #     django-version: "4.0b1"
        #   # Python 3.7 is compatible with Django 4.0b1
        #   - python-version: "3.7"
        #     django-version: "4.0b1"
        #   # Python 3.8 is compatible with Django 2.2+
        #   - python-version: "3.8"
        #     django-version: "1.11.0"
        #   - python-version: "3.8"
        #     django-version: "2.0.0"
        #   - python-version: "3.8"
        #     django-version: "2.1.0"
        #   # Python 3.9 is compatible with Django 3.1+
        #   - python-version: "3.9"
        #     django-version: "1.11.0"
        #   - python-version: "3.9"
        #     django-version: "2.0.0"
        #   - python-version: "3.9"
        #     django-version: "2.1.0"
        #   - python-version: "3.9"
        #     django-version: "2.2.0"
        #   - python-version: "3.9"
        #     django-version: "3.0.0"
        #   # Python 3.10 is compatible with Django 3.2+
        #   - python-version: "3.10"
        #     django-version: "1.11.0"
        #   - python-version: "3.10"
        #     django-version: "2.0.0"
        #   - python-version: "3.10"
        #     django-version: "2.1.0"
        #   - python-version: "3.10"
        #     django-version: "2.2.0"
        #   - python-version: "3.10"
        #     django-version: "3.0.0"
        #   - python-version: "3.10"
        #     django-version: "3.1.0"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip version
        run: |
          python -m pip install -U pip

      - name: Upgrade django version
        run: |
          python -m pip install "Django~=${{ matrix.django-version }}"

      - name: Python and Django versions
        run: |
          echo "Python ${{ matrix.python-version }} -> Django ${{ matrix.django-version }}"
          python --version
          echo "Django: `django-admin --version`"
